### ISSUE TITLE
[Feature Request] HxD-style keyboard shortcuts and comparison options?

### ISSUE THREAD

**Issue by Darthagnon** [solemnwarning/rehex#103]
I found the current method of comparing two files in ReHex to be somewhat unintuitive (probably because there were no menu options to hint at it):
- ```Ctrl``` + ```A```/selection >> Right click >> Compare
- Repeat the above for second file
- No visible "Next/Previous difference" option???

HxD has a decent comparison system with some nice keyboard shortcuts - any chance these could be implemented in ReHex?

HxD Shortcuts:
- ```Ctrl``` + ```K```: Compare (opens data source window, which defaults to the content of the first two tabs)
- ```F6```/```Shift```+```F6```: Next/Previous difference (when comparing)
- ```Ctrl``` + ```F```: Search (opens search window, where one can select to search Text, Byte Sequence or Value)
- ```F3``` / ```Shift```+```F3```: Search again / Search again backwards

An improvement over HxD would be if ReHex's search function could highlight/show all occurences of a particular query.
EDIT: Just realised that there's the "Highlight data matching selection" option. Sweet! Is there any way to jump between highlighted matching options and comments?

**Comment by solemnwarning** [comment]
Shortcuts added to the `diff-improvements` branch:

Ctrl+K: Compare whole file
Ctrl+Shift+K: Compare selection
F6: Next difference
Shift+F6: Previous difference
