### ISSUE TITLE
[Proposal] Changes for better msys2 support

### ISSUE THREAD

**Issue by hgdagon** [solemnwarning/rehex#110]
### note: I was just going to propose a simpler method for building with msys2, but this turned into a rant of my experience with building statically.

So, I just found out about this yesterday, and tried building it. The instructions for windows are a bit confusing. I don't understand why we're getting the toolchain separately, using msys2 just as a bash shell, and building each library one by one, exporting the toolchain each time. Msys2 provides prebuilt libraries (both shared and static) as well as the MinGW-w64 toolchain. I already have msys2 installed, and I used that, so here's some simpler instructions dor msys2.

1. Download and install msys2.
2. Run `pacman -Syuu` (Notice the second `u`, compared to Arch Linux).
2.1 Restart msys2 and run `pacman -Syuu` again, if prompted.
3. Now run either the MinGW32 or the MinGW64 shell, depending on which architecture you'd like to build for.
4. Run this command (`jbigkit` needed for linking wxWidgets statically).
```
pacman -S --noconfirm --needed base-devel git mingw-w64-$(arch)-{toolchain,wxWidgets,jansson,capstone,jbigkit}
```
5. clone the repo and run `make -f Makefile.win`.
```
git clone https://github.com/solemnwarning/rehex && cd rehex && make -f Makefile.win
```

I had to make a few changes to build statically.
Line 19 in `Makefile.win` (just rearrange and don't switch back to dynamic): 

`LDLIBS         := -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lwinpthread`

And line 36 in `Makefile`:

`LDLIBS := $(WX_LIBS) $(LDLIBS) -ljansson -lcapstone`

This ensures that `jansson` and `capstone` are also linked statically.

These changes should have no impact on other platforms. But we're still linking `wxWidgets` dynamically, so I also changed line 31 in `Makefile` to:

`WX_LIBS     := $(call shell-or-die,$(WX_CONFIG) --static --libs base core aui propgrid adv)`

This way I get a static build 35.7MB (13.8MB when stripped).

## The problems

I have nothing to test the OSX build on, but I have a laptop running Manjaro, so I tested there.

The provided `wxgtk2` and `wxgtk3` packages don't have any static libraries, which is fine, if we're not realeasing out, but that obviously means that `--static` switch isn't portable. I think moving that line to `Makefile.win` and defining `WX_LIBS` in `Makefile` only if it hasn't been defined before would be a good solution.

The other problem might be specific to Arch-based distros: Seemingly for compatibility with `wxgtk2`, in `wxgtk3` package `wx-config` is renamed to `wx-config-gtk3`. There needs to be a check for that as well.

**Comment by hgdagon** [comment]
Also, here's a few issues I noticed:

1. Defender detected suspicious behavior Win32/DefenseEvasion.WI!ml after running.
2. Color scheme was set to `system` on first run, but was light, even though my system is dark.
3. Separate strings window is very nice, but can't organize by string.
4. No codepage changing support.

**Comment by learn-more** [comment]
> Also, here's a few issues I noticed:
> 
> 1. Defender detected suspicious behavior Win32/DefenseEvasion.WI!ml after running.
> 2. Color scheme was set to `system` on first run, but was light, even though my system is dark.
> 3. Separate strings window is very nice, but can't organize by string.
> 4. No codepage changing support.

2: #101 
4: #106

**Comment by solemnwarning** [comment]
I build all the libraries manually rather than using the msys packages because I didn't know it *had* static libraries for all of the packages, and originally I was planning on making the build process not require msys - just the toolchain/libraries, but wx-config being a shell script kinda blew that plan out of the water.

The upstream mingw-w64 project stopped bothering to make builds a year or two ago as well, so I'd even been considering switching to MSVC for the official Windows builds.

How far behind do msys packages tend to lag? wxWidgets 3.2.0 will hopefully be out soon, which will fix some minor issues on Windows. A very recent build of Capstone is also needed to get 68k support.

**Comment by hgdagon** [comment]
@solemnwarning I can't say I'm sure the static builds are available for *all* packages, but most of them come prepackaged with both. The ones used in this project, certainly do contain static libs. All of that static/dynamic thing, as well as being behind massively depends on the package maintainer. But here's what we have as of right now:

Package | Version
--------- | --------
mingw-w64-x86_64-wxWidgets | 3.0.5.1-1
mingw-w64-x86_64-wxmsw3.1 | 3.1.3-1
mingw-w64-x86_64-jansson |  2.13.1-1
mingw-w64-x86_64-capstone | 4.0.2-1 

I used the `wxWidgets` package, since it's the stable one. The 32-bit versions are also up-to-date (they get updated simultaneously)
You can check the versions and see the list of files in all packages over at https://packages.msys2.org/
Usually, if a package is behind for a long time, all it takes is opening an issue with the package maintainer, and, provided there's no roadblock,  they get updated pretty fast. I myself never had to do that, though, everything is usually pretty up-to-date.

**Comment by solemnwarning** [comment]
The CI system is now making builds with only msys2 packages and the build instructions have been ~~updated~~decimated.

Thanks for pointing this out, made adding Lua a bit less painful!
