### ISSUE TITLE
Crash after inserting and deleting bytes

### ISSUE THREAD

**Issue by smokris** [solemnwarning/rehex#113]
Steps to reproduce crash:

- Launch REHex 0.3.1
- In the untitled document window, type some hex (e.g., `f0`)
- Edit > Select All
- Either press delete, or Edit > Cut, to clear the entire contents of the document
- Start typing more hex — **crash**: [REHex_2021-01-06-145039_joku.txt](https://github.com/solemnwarning/rehex/files/5777873/REHex_2021-01-06-145039_joku.txt)

The crash is consistently reproducible on macOS; I haven't tested on other OSes.

**Comment by solemnwarning** [comment]
Thank you for reporting this, now fixed on master.

**Comment by smokris** [comment]
Thanks!
