### ISSUE TITLE
[bug] Unable to open file with non-ASCII path

### ISSUE THREAD

**Issue by drygdryg** [solemnwarning/rehex#117]
When I try to open a file located in the path "/home/victor/Рабочий стол/file.bin" I get an error that the file was not found.
![image](https://user-images.githubusercontent.com/43933400/104275090-3df0c300-54b3-11eb-98ae-80bef96fac47.png)

Commands (both don't work):
`rehex /home/victor/Рабочий\ стол/file.bin`
`rehex "/home/victor/Рабочий стол/file.bin"`

Confirmed versions: 0.3.1, latest from the master (r712.e5dbba7)
OS: Arch Linux x86_64

**Comment by solemnwarning** [comment]
Thanks for reporting this, can you give it another try?

**Comment by drygdryg** [comment]
Thanks, the problem has been fixed.
And thanks a lot for Rehex!
