### ISSUE TITLE
[bug] bytes in preview disappear when selecting them

### ISSUE THREAD

**Issue by zocker-160** [solemnwarning/rehex#119]
It seems like this bug got introduced by 910e1da13d415422f52a1cbf3ac9368747565e6e, since it does work fine with 24d75ebc7ba76e1afe9d082c400c3c1796ded046 and prior.

short clip demonstrating the issue:
https://user-images.githubusercontent.com/36563538/105863084-ca8d9c00-5ff0-11eb-9d46-37db8bb86873.mp4

this is how it worked before 910e1da13d415422f52a1cbf3ac9368747565e6e
https://user-images.githubusercontent.com/36563538/105863222-f3ae2c80-5ff0-11eb-968a-8f72f863e3d7.mp4

It still persists on the current master.

**Comment by solemnwarning** [comment]
Are you using one of the packages from Buildkite or compiling it yourself? I can't reproduce the behaviour shown in the video.

**Comment by zocker-160** [comment]
building myself using `make`

**Comment by solemnwarning** [comment]
Does it happen with all files, or only some? Anything specific about your system you can think that might be causing it?

**Comment by zocker-160** [comment]
ok I just did some further testing including multiple VMs and I think this has to do something with my system, since I cannot reproduce anywhere else.

When I move the same binary from my machine to a different one, the error is not there.

I am using a plain Ubuntu 20.04 installation and it happens with any file I input and it is reproducible when I move between the two commits I mentioned above,

**Comment by zocker-160** [comment]
I now do have the exact same issue on Windows as well....

https://user-images.githubusercontent.com/36563538/133074785-4a83cbd4-a6fc-4860-88ac-b447103a36f1.mp4

Is there really nobody that can reproduce this problem? -_-

**Comment by solemnwarning** [comment]
It must be *some* multiple of bytes or screen resolution or *something*... but I have no idea what :(

Tried the latest release on my Windows box and I'm still not seeing it.

**Comment by zocker-160** [comment]
I updated to 0.4.0 and the issue is gone!!

https://user-images.githubusercontent.com/36563538/147106197-dd5f131a-f98b-41e8-b4ab-2a96965fedb9.mp4

Whatever you did, thank you :heart: :heart:

**Comment by solemnwarning** [comment]
I have no idea how that got fixed, I just hope it stays that way for you xD
