### ISSUE TITLE
Missing font size setting in 0.3.1

### ISSUE THREAD

**Issue by marco-calautti** [solemnwarning/rehex#121]
I installed version 0.3.1 in Fedora 33 using the copr repo, but I cannot see the increase and decrease font size options in the View menu.

-EDIT- Nevermind, It seems it did not manage to get included in this version. I built from source.

**Comment by solemnwarning** [comment]
Its not... yeah you found it :)

There are also RPM packages of the Git branches on the Buildkite job if you want to use it that way.

**Comment by marco-calautti** [comment]
Could you provide a link?

**Comment by solemnwarning** [comment]
The latest master is here: https://buildkite.com/solemnwarning/rehex/builds/441

You can get to the build jobs by clicking the build status tick/cross on the Github tree/log pages.

**Comment by marco-calautti** [comment]
Alright, thanks!

**Comment by solemnwarning** [comment]
Shipped in 0.3.90
