### ISSUE TITLE
Data type headers use a dark color in dark GTK themes

### ISSUE THREAD

**Issue by AlexFolland** [solemnwarning/rehex#127]
**To reproduce:**

1. Set GTK theme to a dark one, like the attached screenshot.
2. Open a file.

**Observed behavior:**

Data type headers use a dark color in dark GTK themes, like in this screenshot:

![image](https://user-images.githubusercontent.com/601517/117560770-88d7ad00-b045-11eb-96b7-4eccd97967c2.png)

**Expected behavior:**

All text is expected to use light colors in dark themes.

**Comment by solemnwarning** [comment]
Could you confirm what wxWidgets version you have and what GTK theme you're using? I get slightly different results on my system, and from the looks of it the behaviour changed between 3.0/3.1

**Comment by solemnwarning** [comment]
Should be fixed on master now.

**Comment by AlexFolland** [comment]
Yes, the fix worked here.  Thanks!

![image](https://user-images.githubusercontent.com/601517/119244701-eed53180-bb27-11eb-8745-a988b1e91438.png)
