### ISSUE TITLE
Is it possible to change font?

### ISSUE THREAD

**Issue by tpn** [solemnwarning/rehex#128]
I can't see any UI options for changing the font; I don't suppose there are any stop-gap measures I could use to affect what font is used via wxWidgets?

If not, I'd like to submit changing font as a feature request, thanks.

**Comment by solemnwarning** [comment]
I'm not sure if there is a way of overriding the font (it uses whatever wxWidgets provides for `wxFONTFAMILY_MODERN`), I don't see any reason not to add an option for it though.

**Comment by tpn** [comment]
Awesome, thanks @solemnwarning!  Much appreciated!
