### ISSUE TITLE
Fix endianness support on FreeBSD

### ISSUE THREAD

**Issue by danfe** [solemnwarning/rehex#133]
You're using seemingly popular `portable_endian.h` header file by Mathias Panzenböck which mishandles modern FreeBSD (it breaks the build); your copy needs the same patch as in sirjuddington/SLADE#1263.

**Comment by solemnwarning** [comment]
I don't have a FreeBSD box handy, but should be fixed now.

**Comment by danfe** [comment]
I've removed my local `sed(1)`-based hack, applied the 98c8013 patch, and the build is fine now, thank you.
