### ISSUE TITLE
Disassembly support for AT&T AMD64 syntax

### ISSUE THREAD

**Issue by cypMon** [solemnwarning/rehex#142]
Hello!
I'd like to know if it it would be possible to add an option to disassembly using the AT&T syntax and not just the intel (the default) one.
According to the [Capstone's guide](http://www.capstone-engine.org/lang_c.html#5-run-time-options), this can be done by using:
`cs_option(handle, CS_OPT_SYNTAX, CS_OPT_SYNTAX_ATT)` after `cs_open`.
As this is an option and not a mode, I don't know how this could be implemented, but would appreciate if you consider adding this option.
Thank you!

**Comment by solemnwarning** [comment]
I'll add it as an option in the next release

**Comment by cypMon** [comment]
Thank you for accepting it!
