### ISSUE TITLE
Interest in using Homebrew for building on macOS?

### ISSUE THREAD

**Issue by mdaniel** [solemnwarning/rehex#157]
Currently, [the macos dependency script](https://github.com/solemnwarning/rehex/blob/0.4.1/tools/mac-build-dependencies.sh) is a lot of shell but the dependencies it wants are currently in Homebrew, which could save potential contributors a lot of CPU time by not downloading and rebuilding them:

* [capstone](https://formulae.brew.sh/formula/capstone#default)
* [jansson](https://formulae.brew.sh/formula/jansson#default)
* [libunistring](https://formulae.brew.sh/formula/libunistring#default)
* [lua](https://formulae.brew.sh/formula/lua#default)
* [luarocks](https://formulae.brew.sh/formula/luarocks#default)
* [wxWidgets](https://formulae.brew.sh/formula/wxwidgets#default)
* maybe cpanminus, too, I am not very fluent in cpam-ery

I can appreciate that some people have strong feelings about Homebrew, so I thought it best to ask if you were building those deps manually on purpose, or would entertain a patch for a Homebrew-based macOS build

**Comment by solemnwarning** [comment]
I'm not really familiar with Homebrew (or any of the other package managers) on macOS, but I didn't want to depend on any particular one for setting it up, hence the script building everything from scratch (and not installing any of it system-wide).

I wouldn't be against including an alternate script for Homebrew users, but it might wind up outdated and non-working (like the MSVC stuff currently is).

**Comment by mdaniel** [comment]
That makes sense, thanks for your reply. I'm going to close this issue
