### ISSUE TITLE
Parse error reports only at the function level, not at the parse failure location

### ISSUE THREAD

**Issue by mdaniel** [solemnwarning/rehex#158]
I was trying out the binary-template plugin after your announcement on Reddit and encountered a parse error. It took me forever to boil it down to a reproducible case because the error message implied it was the function signature that was the problem. However, it turned out one of the statements _down in_ the function that was the problem all along

Given:
```c
void thisFunctionIsBad() {
    local char c = '0';
}
```
it produces
> ...ns/REHex.app/Contents/PlugIns/binary-template/parser.lua:109: Parse error at /Applications/REHex.app/Contents/PlugIns/binary-template/templates/bob.bt:1 (at 'void thisFu')

instead of

> Parse error at /Applications/REHex.app/Contents/PlugIns/binary-template/templates/bob.bt:2 (at "=  '")

or similar

In hindsight (as with all good bugs!), I noticed that the docs actually don't mention character literals, so it was my "C muscle memory" leaking through. Given that it appears to be inspired by the 010 language, [their strings page](https://www.sweetscape.com/010editor/manual/ArraysStrings.htm) does seem to imply that single quotes are allowed, but it's unclear if they differ from just using `"` or when one would use which style

**Comment by solemnwarning** [comment]
oop, thanks for pointing these out. I'll try to get the error reporting ahd character literals sorted out tomorrow.
