### ISSUE TITLE
intX_t behaving as uintX_t variants

### ISSUE THREAD

**Issue by mdaniel** [solemnwarning/rehex#160]
Given:
```c
local int8_t i; // same for int16_t int32_t but NOT int64_t
for (i = 2; i >= 0; i--) {
    Printf("inner(%d)\n", i);
    if (i > 100) break;
}
```
without that `break`, it would never terminate since it emits
```
inner(2)
inner(1)
inner(0)
inner(255)
```

Thankfully(?), `local char i` behaves the same, so it seems to be mostly systemic to the non `unsigned` types (except `int64_t` does actually behave correctly, emitting `inner(-1)`)

**Comment by solemnwarning** [comment]
I thiiiink I fixed it... new tests are passing anyway!
