### ISSUE TITLE
[Feature] add bitarray to data types

### ISSUE THREAD

**Issue by zocker-160** [solemnwarning/rehex#167]
It would be really useful to have bitarray as a data type available so that for example `0x8030` would show as `[1000000000110000]`

![grafik](https://user-images.githubusercontent.com/36563538/165856017-cddaac8f-b486-4b2e-8c33-192d17085a75.png)

**Comment by zocker-160** [comment]
I think this is similar to #155, because displaying like I tried to show in the image above could also add the ability to edit it.

Being able to split it up into smaller bit words would be nice as well I think.

**Comment by solemnwarning** [comment]
This has been waiting a while, but finally underway on the branch where I'm refactoring everything to support bit-aligned sizes/offsets!

![image](https://github.com/solemnwarning/rehex/assets/9392044/94b680d5-ac4c-4015-be49-fd56916eb20d)

I'm debating how this should look - do you think it should retain the hex/text columns on either side like the disassembly (pictured), or utilise the entire row for binary?

**Comment by zocker-160** [comment]
If you ask me, I think it should behave the same as any other data type. 
For example when I select an s8 it looks like this currently:
![Screenshot_20240224_163904](https://github.com/solemnwarning/rehex/assets/36563538/f096d12e-3443-46fc-b770-60fd59794624)

So when selecting type "bitarray" instead, I would expect `[11111111]` on the left (instead of `[-1]` and e.g. `<bitarray8>` on the right (instead of `<s8>`)

**Comment by solemnwarning** [comment]
Merged to master along with a boatload of refactoring to support bit-precision offsets for the cursor position, selections, comments, data type definitions, etc.
