### ISSUE TITLE
Offset of virtual sections overflows into data

### ISSUE THREAD

**Issue by SteveKing** [solemnwarning/rehex#170]
When I have a relatively small file loaded (<4GB) the file offset column is shown as a 32-bit value.  If I set a virtual section with an origin at >4GB and do "Display virtual sections" the offset switches to 64-bit mode but the column does not get any wider. This results in the offset overflowing into the data area. Screenshot attached.

REHex 0.5.1
macOS 10.14.6

![Screen Shot 2022-05-10 at 17 57 16](https://user-images.githubusercontent.com/132885/167728717-aa594e31-7470-4392-a31c-99edc1c89b1c.png)

**Comment by solemnwarning** [comment]
Thanks for pointing that one out, fixed!
