### ISSUE TITLE
Feature request: Support duplicates in binary templates

### ISSUE THREAD

**Issue by bartlibert** [solemnwarning/rehex#174]
Hi,

I have a (proprietary) file format that I want to analyse with binary templates, but I can't seem to find a way to do it without using duplicates, as described [here](https://www.sweetscape.com/010editor/manual/ArraysDuplicates.htm).
I don't necessarily need the "array" functionality described there, but just beeing able to do somethins like this would be awesome:

```
local int i;
for (i=0; i< blockCount; i++) {
   uint16_t x;
   uint16_t y;
   uint8_t chars[10];   
}
```

**Comment by solemnwarning** [comment]
I think you could do that with an array of structs?

e.g.

```
struct Foo {
    uint16_t x;
    uint16_t y;
    uint8_t chars[10];
}

Foo foo[blockCount];
```

Let me know if there's some more subtlety to the format you need to account for.

**Comment by solemnwarning** [comment]
Not an elegant, but I just realised you can do this without changing the interpreter:

```
unsigned char blockCount;
unsigned char arraySizes[blockCount];

struct Block
{
	uint16_t x;
	uint16_t y;
	
	local int chars_size = arraySizes[ArrayLength(blocks)];
	uint8_t chars[chars_size];
};

struct Block blocks[0];

local int i;
for(i = 0; i < blockCount; ++i)
{
	ArrayExtend(blocks);
}
```

**Comment by bartlibert** [comment]
Hmm yeah, that seems to work. But the possibility to passing struct arguments looks really nice!

**Comment by solemnwarning** [comment]
I'm gonna go ahead and close this since I think the struct argument passing thing ticks all the boxes for you? Feel free to re-open if there is another use for duplicate variables to consider.
