### ISSUE TITLE
0x0D bytes are not pasted

### ISSUE THREAD

**Issue by Ritterbrater** [solemnwarning/rehex#192]
Hi,

nice project! I was looking for a longer time for a great open source hex editor. Now I found one.
But I have an unkind issue:
Version: 0.5.4 and earlier
OS: Win 10 x64
Description:
- I copy a byte array that also contain (`\r\n`) `0x0D 0x0A`
- When I paste the byte array all the `0x0D` bytes are gone

Expected behavior:
- All bytes are pasted

I hope I did not oversee any configuration (like the fixed number of bytes per line) ;)

Before somebody asks: Why not using a text editor? - Large file with mixed binary and text data.

Thank you!

**Comment by solemnwarning** [comment]
That's kinda weird... where exactly are you copying to/from?

If you copy/paste in the hex area, you should get a string of hex bytes and in the text area, a string of any printable characters in the selection... 0x0D 0x0A seem to copy/paste fine for me in both.

**Comment by Ritterbrater** [comment]
Ah ok, I see a different behaviour, depending on copy/paste from the text hex view and from the bin view. Details:
- I created a simple text with multiple lines with win notepad (to be sure to have win line endings)
- I disable overwrite mode to append the data (seems to have not influence)
- When I copy and paste the data inside the hex view on the left everything works fine
- When I copy and paste the data inside the text representation on the right, the 0x0D is gone

**Comment by solemnwarning** [comment]
I've done some thinking on this, and I don't think there's a good way to fix it.

I considered implementing a composite data type for when "text" is copied into the clipboard, which would allow for exporting platform-native text to other applications, but also the raw data for pasting back into rehex - this would fix the case of preserving line endings when copying/pasting within rehex, but would create other subtle edge cases where text encodings differ, or characters on the source side cannot be represented on the destination side.

So I think allowing the line endings to change when copying/pasting text is the lesser evil, which some other tools also do: https://github.com/Microsoft/vscode/issues/53820#issuecomment-420581522
