### ISSUE TITLE
When deleting a comment with nested comments, allow for deletion of nested comments too

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#198]
When deleting a comment with a collection of nested comments, right now if you delete the parent then all the nested comments still remain. 

It would be helpful if the app gave a prompt in such a case asking if you want to delete nested comments too, or alternatively, on the context menu give an extra option for "Delete Comment and Nested" or something - not sure at all about the wording.

**Comment by solemnwarning** [comment]
Implemented in e3f691f4a9097a07db579417414e65bee8d7bb0c.
