### ISSUE TITLE
error installing from source in Linux

### ISSUE THREAD

**Issue by kermitdafrog8** [solemnwarning/rehex#206]
During make install I get the following error messages.  Not sure why it's seeing busted for MinGW in Linux.
```
make[1]: Entering directory '/tmp/rehex-0.5.4/plugins/binary-template'
Makefile:52: *** Neither busted or busted.bat found in PATH.  Stop.
make[1]: Leaving directory '/tmp/rehex-0.5.4/plugins/binary-template'
make: *** [Makefile:551: install] Error 2
```

**Comment by solemnwarning** [comment]
What happens if you just run `busted`?

**Comment by kermitdafrog8** [comment]
Is it looking for this https://lunarmodules.github.io/busted/   ?

**Comment by solemnwarning** [comment]
Yes.

FYI it only gets used for running the tests, so if you're not doing that you can probably just specify `BUSTED=false` in the environment.

**Comment by kermitdafrog8** [comment]
Ok I'll go with that in my build script.  Don't think I really need to do the test portion.

**Comment by solemnwarning** [comment]
I'm gonna go ahead and assume it worked for you since there's been no more posts here.
