### ISSUE TITLE
Open the source file when the rehex-meta file is opened (allow associating the file type with the program)

### ISSUE THREAD

**Issue by Poikilos** [solemnwarning/rehex#207]
Actual behavior:
- When the program opens a rehex-meta file, it opens the project file itself (such as 'something.bin.rehex-meta")--The JSON is displayed as binary.

Expected behavior:
- If the opened file is a rehex-meta file, open the corresponding binary file (such as "something.bin") if present.

Steps to reproduce issue:
1. Create a file named "something.bin" and save it using rehex to generate a "something.bin.rehex-meta" file.
2. To test on a command line, run `rehex something.bin.rehex-meta` then skip steps 3-4 below.
3. Associate rehex-meta file with rehex.
4. Double-click the rehex-meta file.

**Comment by solemnwarning** [comment]
Implemented in a6f3dd10c39af6ccd9bcb8552f0481c977c29f15
