### ISSUE TITLE
Icons in the toolbar on macOS are blurry

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#21]
I would post a screenshot but my mac won't let me, so you'll just have to take my word for it :)

**Comment by solemnwarning** [comment]
Possibly fixed by aaeaa54e38a6be5bfc7709267f32ed685c072cd3 (toolbar-icon-fix branch), but also makes icons really tiny on Linux and isn't tested on Windows yet.

**Comment by hogsy** [comment]
Icons still look pretty blurry on macOS but a little better than before.

Dunno if this is at all useful? https://forums.wxwidgets.org/viewtopic.php?t=44534

**Comment by solemnwarning** [comment]
Looks like its an issue with either wxArtProvider or the stock icons themselves on OS X. Even in the artprov sample, loading bitmaps as wxART_TOOLBAR returns blurry 32x32 images:

![blurry](https://user-images.githubusercontent.com/9392044/53347500-1d481000-3911-11e9-9856-025f86db9b03.png)

**Comment by solemnwarning** [comment]
wxWidgets ships the Tango icons, in 16x16 and 24x24, chosen as the main sizes used by GTK/Windows. Mac UI guidelines recommend 32x32 toolbar buttons, which is getting scaled from the 24x24 icon (https://github.com/wxWidgets/wxWidgets/blob/master/src/common/arttango.cpp).

Need to try it out with the 32x32 icons... maybe patch wxArtProvider to include 32x32 (and 64x64 for "Retina" displays?)?

**Comment by solemnwarning** [comment]
61696493c5250986ca2f5780fc477ceb3ecd025a looks fine on my test VM. How about your actual Mac (does it have a "Retina" display?), @hogsy?

**Comment by hogsy** [comment]
Looks much better on macOS now.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1946366/53412048-28a64480-39c0-11e9-86c4-2090df3a375e.png">

**Comment by solemnwarning** [comment]
Merged to master in d0d69d8e5de0f84497b29f420d995b5ca310722f
