### ISSUE TITLE
Add copy/export options to strings table

### ISSUE THREAD

**Issue by stdust** [solemnwarning/rehex#210]
I was very surprised because there were many unique features that were not found in the commercial hexa editor program Thank you for showing us a great program

I'd like to make a suggestion I hope I can select multiple values of the string tab so that I can copy them and export the values of the string tab to a txt file

We are using the program you provided Thank you. Have a nice day

**Comment by solemnwarning** [comment]
Done!

![image](https://github.com/solemnwarning/rehex/assets/9392044/cb73f8e8-e77b-4546-99f4-a3f4bca63b74)
