### ISSUE TITLE
How to quickly add 0x00 data?

### ISSUE THREAD

**Issue by Char11e** [solemnwarning/rehex#213]
My data ends at 0x16F401DAFFF.
I want to quickly fill every bit with 0's.
Fill in the start address is 0x16F401DB000 to end address is 0x17FCE8FFFFF.

**Comment by solemnwarning** [comment]
The only way to bulk-insert new bytes at the moment is by pasting them from the clipboard. I might add an "Insert range" command alongside the "Fill range" that currently exists (or add an insert toggle to the latter).

**Comment by solemnwarning** [comment]
I've added an overwrite/insert toggle to the "Fill range" tool for the next version:

![image](https://github.com/solemnwarning/rehex/assets/9392044/18160dbe-b0ba-4c26-92cc-5c024a3eef93)
