### ISSUE TITLE
enums in binary templates are documented to support trailing comma, but don't actually support that

### ISSUE THREAD

**Issue by wilcoxjay** [solemnwarning/rehex#216]
The first example of an enum in a binary template from the manual is

```
enum simple_enum_type
{
	ENUM_ONE,
	ENUM_TWO,
	ENUM_THREE,
};
```

with a trailing comma after `ENUM_THREE`, but I couldn't get this to work. I get a parse error at the close brace.

**Comment by solemnwarning** [comment]
Thanks for pointing that out! Fixed.
