### ISSUE TITLE
Calculate checksum from selection

### ISSUE THREAD

**Issue by selurvedu** [solemnwarning/rehex#219]

**Comment by solemnwarning** [comment]
Any particular algorithms you think would be useful here?

**Comment by selurvedu** [comment]
Definitely CRC32 for me. Here are some other popular options:

https://github.com/WerWolv/ImHex/blob/b71a77677058b545d3b17104453ce3d61cd10865/plugins/builtin/source/content/hashes.cpp#L170
https://www.sweetscape.com/010editor/manual/CheckSum.htm

Generally I'm more interested in algorithms that produce shorter checksums (e.g. Adler-32 and other CRCs)  as I see them being used more often in things I'm reverse engineering.

**Comment by solemnwarning** [comment]
Merged to master.
