### ISSUE TITLE
Very interesting app but how would I support the MIDI.bt file?

### ISSUE THREAD

**Issue by perivar** [solemnwarning/rehex#220]
I tried to convert the Midi.bt file to this format, but failed.
The midi template contains so manye things that I was unable to get working. 
Like break, sizeof and bitfields.
https://www.sweetscape.com/010editor/manual/Bitfields.htm

I would really appriciate if you showed how this could be done:
https://www.sweetscape.com/010editor/repository/templates/file_info.php?file=MIDI.bt

Thanks,

**Comment by perivar** [comment]
Excellent, thanks!

The last code I am unable to convert is the section using break;
How would you conditionally read another variable when break cannot be used?
I.e. like the DeltaTime struct:
struct DeltaTime
{
    local uint total = 0;
    char t0;
    total += t0 & 0x7f;
    if (!(t0 & 0x80))
        break;

    total <<= 7;
    char t1;
    total += t1 & 0x7f;
    if (!(t1 & 0x80))
        break;

    total <<= 7;
    char t2;
    total += t2 & 0x7f;
    if (!(t2 & 0x80))
        break;

    total <<= 7;
    char t3;
    total += t3 & 0x7f;
    if (!(t3 & 0x80))
        break;
};

**Comment by solemnwarning** [comment]
You can selectively put variable definitions inside 'if' statements, so the lack of a break keyword in struct definitions itself isn't a problem, but 'local' variables declared in structs won't be exposed as members, so where the template does `m_length.total` wouldn't work.

In rehex templates, I'd suggest doing something like the following at the moment:

```
unsigned int read_DeltaTime()
{
    local unsigned char byte = ReadU8();
    FSkip(1);

    local unsigned int value = byte & 0x7F;

    for(local int i = 0; i < 3; ++i)
    {
        if((byte & 0x80) != 0)
        {
            byte = ReadU8();
            FSkip(1);

            value <<= 7;
            value |= (byte & 0x7F);
        }
    }

    return value;
}
```

And then in place of `DeltaTime m_length;`, you can read/skip the size with `local unsigned int length = read_DeltaTime();`

**Comment by solemnwarning** [comment]
> Maybe you could have a repository for working templates?

I've thought about it a bit, but I don't think there's a demand for it right now. Would you be happy for me to include the above `MIDI.bt` script if/when it happens?

**Comment by perivar** [comment]
Yes thats fine

/Per Ivar
