### ISSUE TITLE
[Feature Request] Colorize HEX values

### ISSUE THREAD

**Issue by PROPHESSOR** [solemnwarning/rehex#223]
In radare2 there's color highlighting for hex values (green for 0x00, red for 0xFF, blue for 0x7F, yellow for ASCII, etc).
![image](https://github.com/solemnwarning/rehex/assets/19251320/33a44748-d84e-4bdd-b5af-6863e737fcfe)

It's convenient when you work with non-ascii data to "feel" the values.

In addition, it would be nice to have some heatmap-like gradient colorization of the values. For example, from blue for 0x00, through red for 0x7F, to white for 0xFF.
![image](https://github.com/solemnwarning/rehex/assets/19251320/a5affe2a-fc52-44f0-a151-1a531d92960f)

**Comment by solemnwarning** [comment]
Still an early WIP, but a preview of how the UI for this is coming along:

![image](https://github.com/solemnwarning/rehex/assets/9392044/ccbc4091-5520-4d5c-9354-5e5e641740e8)

The intent here is that you will be able to define different value colourisation profiles which define solid colours to use for bytes, or start/end colours to apply a gradient over a range and switch between them from the view menu.

**Comment by solemnwarning** [comment]
![image](https://github.com/solemnwarning/rehex/assets/9392044/06f5d02e-c6bf-4d53-8198-4a833b9995ef)

**Comment by solemnwarning** [comment]
Finished and merged into master.
