### ISSUE TITLE
Compare window shows data from start of file rather than selection when "Collapse matches" option is enabled

### ISSUE THREAD

**Issue by PROPHESSOR** [solemnwarning/rehex#224]
- File A
![image](https://github.com/solemnwarning/rehex/assets/19251320/bf820798-6d13-484b-abde-7fea0322bec5)

- File B
![image](https://github.com/solemnwarning/rehex/assets/19251320/f368b06b-47ef-4994-a656-aeddb66fb5ae)

- The comparison
![image](https://github.com/solemnwarning/rehex/assets/19251320/40539f8a-0fe0-4a43-8dbe-91f1c004f649)

![image](https://github.com/solemnwarning/rehex/assets/19251320/f4f2bf13-91f2-422a-9fef-f2ecdf3223a8)

**Comment by solemnwarning** [comment]
Thanks for spotting this!
