### ISSUE TITLE
[Feature Request] Highlight improvements

### ISSUE THREAD

**Issue by PROPHESSOR** [solemnwarning/rehex#227]
- Dimm highlight colors for dark theme (they're so bright)
![image](https://github.com/solemnwarning/rehex/assets/19251320/9260ad69-0a00-46f8-953a-177705d1c9db)
- Add more colors: blue, cyan, etc.
- Add automatic highlights for some HEX pattern
- Add more highlight methods: text color, background color, underline color, etc

**Comment by solemnwarning** [comment]
Which of these colour palette(s) do you prefer?

![c100](https://github.com/solemnwarning/rehex/assets/9392044/fbdfcb9d-9c85-4dbe-8c46-97056457bd5b)
![c90](https://github.com/solemnwarning/rehex/assets/9392044/661a57c5-62d6-4188-8419-1eefe8a42b7c)
![c80](https://github.com/solemnwarning/rehex/assets/9392044/b7d4207b-78c1-4231-82eb-026792a3de08)
![c70](https://github.com/solemnwarning/rehex/assets/9392044/30ff7525-ab66-4dee-a76c-c2dd3ca7a8ee)

**Comment by solemnwarning** [comment]
I've made all the changes I'm planning on making to highlights for the next release:

- Reduced default intensity of highlight colours when using dark colour schemes
- Allow changing highlight colours, defining custom ones and assigning labels
- Maintain file-specific lists of highlight colours/labels
- Added shortcuts for assigning highlights (Ctrl+1,Ctrl+2,etc by default)

Please do open further issues if you still feel the need for the other changes once you've used the above for a little while.
