### ISSUE TITLE
ReHex v0.62 gets crashing on Windows XP SP3

### ISSUE THREAD

**Issue by LordGarfio** [solemnwarning/rehex#239]
Versions 0.61.0 and 0.61.1 load without problems on Windows XP SP3 32Bits, however, version 0.62.0 fails.

**rehex-0.61.0-win-i686.zip**
![rehex-0 61 0-win-i686_2024-07-22_162130](https://github.com/user-attachments/assets/74a6dcd9-2466-4c2d-86ff-f23a0ff990d5)

**rehex-0.61.1-win-i686.zip**
![rehex-0 61 1-win-i686_2024-07-22_162457](https://github.com/user-attachments/assets/813b90e0-4138-4fa3-8654-0d513d97f35d)

**rehex-0.62.0-win-x86.zip**
![rehex-0 62 0-win-x86_2024-07-22_162647_](https://github.com/user-attachments/assets/39e20e7c-a5ca-4e04-8769-aeb17b3e0b2b)
![rehex-0 62 0-win-x86_2024-07-22_162706_2](https://github.com/user-attachments/assets/686c5a8a-454a-4092-b44d-4d267e113dbd)

**Error Report Contents
The following information about your process will be reported**
"<?xml version="1.0" encoding="UTF-16"?>
<DATABASE>
<EXE NAME="rehex.exe" FILTER="GRABMI_FILTER_PRIVACY">
    <MATCHING_FILE NAME="rehex.exe" SIZE="19797400" CHECKSUM="0x27F72604" MODULE_TYPE="WIN32" PE_CHECKSUM="0x12E4D95" LINKER_VERSION="0x0" LINK_DATE="07/20/2024 16:19:13" UPTO_LINK_DATE="07/20/2024 16:19:13" />
</EXE>
<EXE NAME="kernel32.dll" FILTER="GRABMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="kernel32.dll" SIZE="993792" CHECKSUM="0xEA0DD182" BIN_FILE_VERSION="5.1.2600.7682" BIN_PRODUCT_VERSION="5.1.2600.7682" PRODUCT_VERSION="5.1.2600.7682" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="5.1.2600.7682 (xpsp_sp3_qfe_escrow.190315-1905)" ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERFILEDATEHI="0x0" VERFILEDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x100F52" LINKER_VERSION="0x50001" UPTO_BIN_FILE_VERSION="5.1.2600.7682" UPTO_BIN_PRODUCT_VERSION="5.1.2600.7682" LINK_DATE="03/19/2019 18:39:07" UPTO_LINK_DATE="03/19/2019 18:39:07" VER_LANGUAGE="English (United States) [0x409]" />
</EXE>
</DATABASE>"

Regards.

**Comment by solemnwarning** [comment]
So much for the new toolchain I switched to for the 32-bit build having better compatibility :facepalm:

Does the crash happen as soon as you start the application? It seems to work in my Windows XP VM (also SP3).

**Comment by solemnwarning** [comment]
Assuming I'm using the tools correctly, the 339750 offset is pointing at `wxAuiPaneInfo::wxAuiPaneInfo()`... nothing in there looks very crashable, so there might be some memory corruption happening earlier in the stack.

Could you send me a crash dump? From what I've read, Process Explorer can be used to generate one on Windows XP while the "foo.exe has encountered a problem and needs to close" dialog is open.

**Comment by LordGarfio** [comment]
> So much for the new toolchain I switched to for the 32-bit build having better compatibility 🤦
> 
> Does the crash happen as soon as you start the application? It seems to work in my Windows XP VM (also SP3).

Yes, the error occurs as soon as rehex.exe is started.

**Mini Dump**
[minidump.dmp](https://github.com/user-attachments/files/16340320/minidump.dmp)

Thanks.

**Comment by solemnwarning** [comment]
Thanks for the crash dump, it looks like the way I have the toolchain set up is targeting newer than intended CPUs (SSE4 level, specifically), which worked for me since I'm virtualising Windows XP on a fairly modern Ryzen system, I'm guessing you're running it on an older CPU?

[rehex-i686.zip](https://github.com/user-attachments/files/16341383/rehex-i686.zip)

Can you give this exe a try and let me know if it works for you?

Thanks

**Comment by solemnwarning** [comment]
Ignore my last post, this one should have even better compatibility.

[rehex-mmx.zip](https://github.com/user-attachments/files/16352398/rehex-mmx.zip)

**Comment by LordGarfio** [comment]
> Thanks for the crash dump, it looks like the way I have the toolchain set up is targeting newer than intended CPUs (SSE4 level, specifically), which worked for me since I'm virtualising Windows XP on a fairly modern Ryzen system, I'm guessing you're running it on an older CPU?
> 
> [rehex-i686.zip](https://github.com/user-attachments/files/16341383/rehex-i686.zip)
> 
> Can you give this exe a try and let me know if it works for you?
> 
> Thanks

This fixed one works on Intel Core 2 Duo T2300.

![ReHex x32 v0 62 0 Win_rehex-i686_fixed](https://github.com/user-attachments/assets/8594553b-bd30-48b6-bb46-2763c80d8248)

**Comment by LordGarfio** [comment]
> Ignore my last post, this one should have even better compatibility.
> 
> [rehex-mmx.zip](https://github.com/user-attachments/files/16352398/rehex-mmx.zip)

MMX works on Intel Core 2 Duo T2300 too.

Thanks you.

![ReHex x32 v0 62 0 Win_rehex-mmx](https://github.com/user-attachments/assets/493a4d84-2b3a-4583-8eba-327539d11866)
