### ISSUE TITLE
Repeatable GoTo Jumps

### ISSUE THREAD

**Issue by PyroSamurai** [solemnwarning/rehex#242]
While the  REHex does have the ability to both go to a static offset and or a +/- offset, it closes the offset goto window after just a single jump.

I often use +/- offset jumps of a specific size when REing archive/image formats, so having to reopen the goto window for every jump is so inconvenient that end up having to use an inferior hex-editor on the side that does let me do repeat jumps then go back to REHex when I find the offset I want.

Anyways, I don't know how hard this is to implement, but I hope you can save me from this dilemma.

**Comment by solemnwarning** [comment]
A few ideas come to mind:

- Adding an option to make the goto dialog non-modal and remain open
- Adding a "repeat last jump" command (with configurable keyboard shortcut)
- Adding a tool panel which is an extended goto offset input with a list of recent jumps to repeat

**Comment by PyroSamurai** [comment]
Personally I would choose whatever is easiest to maintain, but I might have a preference for the tool panel option but that might just overlap with a "marker" type tool panel. The non-modal option is 'good enough'.
Starting to feel like tool panels are become like toolbars.

**Comment by solemnwarning** [comment]
I've implemented the first two ideas:

- "Non-modal 'Jump to offset'" dialog option in the editor preferences
- "Repeat last 'Jump to offset'" command in the Edit menu
