### ISSUE TITLE
Provide the option to display the offset in bytes

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#25]
Either by clicking on the offset at the bottom (so it'll switch it around), or by going into 'View' and yadda yadda.

This would be very handy.

**Comment by solemnwarning** [comment]
I'm guessing "in bytes" means in decimal rather than hex? Sounds sensible, might become an option under "View" to apply to other places where an offset is displayed too.

**Comment by solemnwarning** [comment]
Implemented on master in 2a11cf9d6f17b83daad535d0d661372da5f73a8d
