### ISSUE TITLE
Bitmap image data visualisation

### ISSUE THREAD

**Issue by solemnwarning** [solemnwarning/rehex#29]
This is an idea for a future tool panel. It would render selected data to the screen as a bitmap, including sliders for image width and pixel size, to aid in identifying bitmap images stored inside files.

Colours will be chosen at runtime to provide visible contrast between different values, but also to show similar ones (so a gradient should look like a gradient, for example).

**Comment by solemnwarning** [comment]
A few things to make me sad when I actually do this:

https://en.wikipedia.org/wiki/BMP_file_format#Pixel_format
https://en.wikipedia.org/wiki/Color_depth#8-bit_color

tl;dr: I need to design a UI for describing arbitrary pixel formats, where channels may be in any order, with varying widths, oddball word sizes (e.g. 18-bit pixels), padding, and shit broken up and scattered around because endianness.

**Comment by r3sus** [comment]
Hello. This feature (or similar) was released in open-source [HexEdit by Andrew W Phillips](https://github.com/AndrewWPhillips/HexEdit). 

> Preview view (currently supports most graphics formats: JPEG, PNG, BMP, ...)
Show current RGBA value in bitmap preview when hovering over a pixel
[Source](https://web.archive.org/web/20180319054933/http://www.hexedit.com/roadmap.aspx)

<details><summary> Detailed Description </summary>

.
Source: "Preview view" at [HexEdit Development: HexEdit 5.0](http://hexeditpro.blogspot.com/2016/10/hexedit-50.html) 

"A few years ago a user asked for the ability to preview bitmap files in HexEdit. Using the FreeImage.DLL (see FreeImage Library) I found this feature very easy to add to HexEdit. (It is displayed in another view window like templates or aerial view - either in a split window or a full-size tabbed window.)

The "preview" view shows the graphics file data as it is in memory, so you can play around with file data and immediately see the changes you have made. This is enormously powerful when combined with a template for the file format you are using.

Moreover the HexEdit preview window (just like the Windows photo previewer and other photo viewers) provides:

- zoom
- drag to scroll
- full support for transparency
- different background options for transparency (eg checkboard)
- supports many graphics file formats (see FreeImage Features)

Actually it is better than the Windows photo previewer as it supports many more image file formats (not just bitmap formats) and has more background options.  (Though it does not yet have rotate/flip options.)" - Andrew W Phillips.

</details>

[CodeProject Article](https://www.codeproject.com/Articles/135474/HexEdit-Window-Binary-File-Editor)
[Download](https://github.com/AndrewWPhillips/HexEdit/issues/8)
[More Data](https://gist.github.com/r3sus/df0e4d31d0be1981b5121edc9b2ea5e3)

**Comment by solemnwarning** [comment]
Merged in 22ee07faa2e8d160ddbd9b132db154bb919c7684
