### ISSUE TITLE
Ability to right click on tab and select 'Open File Location' or something along those lines

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#30]
Would be incredibly handy when opening from 'Recent' say several weeks later and you don't know where that file is located.

**Comment by solemnwarning** [comment]
Sounds good.

Doesn't seem to be a wxWidgets way of opening a folder, will have to do it on each platform:

https://linux.die.net/man/1/xdg-open

https://stackoverflow.com/questions/13680415/how-to-open-explorer-with-a-specific-file-selected
https://docs.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shopenfolderandselectitems

https://ss64.com/osx/open.html

**Comment by solemnwarning** [comment]
Merged to master in 41b8bb6280a710364f9bdafae1031bae31a7ff9d
