### ISSUE TITLE
Tool API

### ISSUE THREAD

**Issue by solemnwarning** [solemnwarning/rehex#4]
There should be a pluggable mechanism for adding new tools/functions rather than continually adding more hooks to MainWindow.cpp

Ideas for tools:

- Relative value search (algorithm prototyped)
- File (i.e. file(1))
- Export selection
- Import file
- External tools for disassembly, images, audio, etc
- Bit editor

Existing search and decode table could be updated to use this system.

Plugins would need to be notified of documents being opened/closed/modified, selection changed, etc. Would need to be able to add menu entries, key bindings, create windows/panels, etc and manipulate document. May be dynamically loadable the future, but probably all "plugins" would be statically linked into the binary at this point.

What about interfering with Document rendering process?

**Comment by learn-more** [comment]
How about python or lua?

**Comment by solemnwarning** [comment]
Possibly.

I think the biggest hurdle right now is getting a stable API for plugins to target - there's still too much refactoring churn whenever I implement something new - the side-by-side diff in the last release involved reorganising most of the codebase.

**Comment by learn-more** [comment]
> Possibly.
> 
> I think the biggest hurdle right now is getting a stable API for plugins to target - there's still too much refactoring churn whenever I implement something new - the side-by-side diff in the last release involved reorganising most of the codebase.

And probably another complete overhaul again when adding scripting :)
Maybe it would be best to first come up with a few use-cases, and start on an api from that?

**Comment by learn-more** [comment]
This is very far from being usable, just toying around with python integration:
https://github.com/learn-more/rehex/commits/python_integration

currently it will load the python interpreter (visual studio build only), and it executes a line of python (with output redirected to a new tool window)
there is still a big pile of problems:
* Since the python library is statically compiled into the binary, there needs to be a python distribution somewhere for most of the functionality (hardcoded path for now)
* Toolwindows are per document, but python has one 'global' interpreter
* Nothing is wired up, other than print() output

Additionally, I am not even sure python is the best choice :)
As a language I know it better than f.e. lua, but this seems much simpler to embed (especially since a lot of the standard library can be compiled into rehex, making it more or less standalone).

**Comment by solemnwarning** [comment]
I might look at Lua scripting for the release after next (I want to wind down development on this one soon).

My intent is still to have all the plugin hooks handled in C++ (e.g. the ToolPanelRegistration and DataTypeRegistration classes) - the script interpreters can be wrapped around the same mechanism, with the glue code creating plugin registration classes and forward calls between them, keeping the script bindings modular.

I also think writing some format parsers (e.g. PE and ELF) as scripts which do minimal processing of the file and then set up comments/types/etc will be a good trial run of the system.

**Comment by learn-more** [comment]
I have a very crude lua integration working.
At application start, all *.lua are found, and registered under a 'Plugins' menu item.
When clicking on the menu item, that script is ran (and creates a new h_panel, hence #91 )
Currently this script:
```
print('test1 plugin loaded!')

function init(doc)
    print('title:', doc:get_title())
    print('filename:', doc:get_filename())
    print('dirty:', doc:is_dirty())
    print('buffer_length:', doc:buffer_length())
end
```
results in this:
![image](https://user-images.githubusercontent.com/610685/95664954-510a9480-0b4c-11eb-8901-c7c7b3c85957.png)

**Comment by solemnwarning** [comment]
@learn-more

I haven't gotten round to looking at your Lua prototype properly yet, but I'd like to start looking at getting Lua bindings in after the next release (aiming for late October/early November), and using it to implement (at least) an "analyse PE executable" command (#86).

**Comment by learn-more** [comment]
> @learn-more
> 
> I haven't gotten round to looking at your Lua prototype properly yet, but I'd like to start looking at getting Lua bindings in after the next release (aiming for late October/early November), and using it to implement (at least) an "analyse PE executable" command (#86).

No rush.
I have force pushed a few times but I'll keep it online for the foreseeable future.
I did add very basic kaitai struct test code in lua, which only works on .zip files for now
