### ISSUE TITLE
Add the ability to diff two files or even better, diff a particular part of two files

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#48]
How this could work, is select a segment of one file and copy it. Then go into another file, set the cursor position and right click, then show a "Compare" option.

No idea how this could then be displayed - maybe automatically colour bytes in red that don't match the source.

**Comment by solemnwarning** [comment]
There's probably more polishing to do before release, but merged to master in 3c61b84d7c198ff7055b3428ff0d0375c42e6e9a.
