### ISSUE TITLE
Copy comments across into different documents

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#50]
When right clicking onto the comment into the comments section, provide a copy option (which will copy that comment inc. all nested comments as well. Which I can then paste into another document.

![image](https://user-images.githubusercontent.com/1946366/75112219-9324ab80-5639-11ea-9130-ddd62913b1d6.png)

And add a button to copy here as well? If not might be worth looking at adding an option to right click the comment within the hex view and then provide a copy option there.

![image](https://user-images.githubusercontent.com/1946366/75112232-acc5f300-5639-11ea-8944-db5f4dda311e.png)

**Comment by solemnwarning** [comment]
Merged to master in d668efede4d78f42812daad1a05813756d374cfb.

Can copy comments from comments panel context menu and also from context menu when right clicking comments in the document.
