### ISSUE TITLE
Support PatternMatchHighlight feature from 'bless'

### ISSUE THREAD

**Issue by ALSchwalm** [solemnwarning/rehex#51]
The [bless](https://github.com/afrantzis/bless) hex editor supports a feature it calls "PatternMatchHighlight". This just highlights bytes that match the currently selected ones. For example:

![2020-03-12-230304_938x639_scrot](https://user-images.githubusercontent.com/1063999/76588711-af3ba000-64b5-11ea-86b4-d74989ef2515.png)

I find this really helpful when reverse-engineering arbitrary binary formats, as it can help determine a bit about the layout of repeating structures.

**Comment by solemnwarning** [comment]
Implemented in 400c28d6bee6727925fecad100fee58f90f29a29. Enable using "Highlight data matching selection" toggle under View menu.
