### ISSUE TITLE
Setup Travis CI for build AppImage (portable binary package for Linux)

### ISSUE THREAD

**Issue by Symbian9** [solemnwarning/rehex#54]
Please, setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

- AppImage Docs - https://docs.appimage.org/

### TODO

0. [ ] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any AppImage packaging questions & support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by solemnwarning** [comment]
I'll have a read through the AppImage docs later today.

Mind if I ask what distribution(s) you use? I started putting everything in place for building Debian/Ubuntu/Redhat packages a while ago, but wasn't sure there was enough interest in Linux binaries at the time.

**Comment by Symbian9** [comment]
> Mind if I ask what distribution(s) you use?

I would highly recommend to use Ubuntu 14.04 Trusty (if possible):

- https://github.com/leozide/leocad/blob/master/.travis.yml

**Comment by solemnwarning** [comment]
I more meant which distribution(s) you run on your computers. Is there a reason you would prefer an AppImage package over a native distribution package?

**Comment by Symbian9** [comment]
> Is there a reason you would prefer an AppImage package over a native distribution package?

AppImage is portable, so it would not touch my system configuration.

**Comment by solemnwarning** [comment]
Its been a while, but AppImage builds are now generated as part of the CI pipeline on each commit.

**Comment by Symbian9** [comment]
> but AppImage builds are now generated as part of the CI pipeline on each commit.

Great!

May it be uploaded as `continuous` pre-release build assets?

- https://github.com/probonopd/uploadtool
  - https://github.com/probonopd/uploadtool/releases/tag/continuous
