### ISSUE TITLE
Migrating to cmake

### ISSUE THREAD

**Issue by learn-more** [solemnwarning/rehex#63]
Would you consider migrating to something like cmake,
instead of hand-crafted makefiles?

**Comment by solemnwarning** [comment]
I like Makefiles. They're pretty much universal on UNIX platforms and (if properly written) have the same targets and environment variables to control what they do.

My experience with CMake on the other hand, is every project does things differently, so first I need to go through the build instructions (if they exist) to figure out what can be configured and how, then find out they targeted a version of CMake that only came out 5 minutes ago, so it won't go ahead anyway.

What functionality of CMake are you after that the Makefiles don't provide? If there is something missing I can add it.

**Comment by learn-more** [comment]
The ability to create a visual studio solution file is what I would like this for.

**Comment by solemnwarning** [comment]
I started work on an MSVC port a while back (using a hand-rolled solution at the time). Some code changes are on the `msvc` branch, but its so old most will probably need redoing on top of master.

The solution needs to be configured such that the sources under `src/` have separate builds with `UNIT_TEST` defined, as a few of the tests redefine private symbols to be public to check things (needs revisiting) and that breaks with the MSVC ABI.

Also MSVC has no support for 64-bit off_t. The only ways I could think up to work around it were either rolling my own off_t type, which typedef's to off_t everywhere else and int64_t on Windows, or defining and undefing off_t to int64_t at the start/end of each header/source file. Both options are horrible, so I haven't looked into it recently.

**Comment by learn-more** [comment]
Okay, so if I were to spend time getting this to work under msvc (using 2019 CE now, is that ok?) you would not instantly reject a PR?

**Comment by solemnwarning** [comment]
Changes to get it working under MSVC would be good. Especially if you think of a clean way around the 64-bit off_t issue :)

A static solution file would also be fine for the first pass, in the long run I would probably look at writing a script to generate one from the Makefile, then include the solution generated by that in the repo whenever the Makefile changes.

Just had a quick look back through my notes from the time in case there was anything helpful there, all I found was the command I (probably) used to configure LLVM to build for MSVC:

```
cmake .. -DCMAKE_INSTALL_PREFIX=C:\vc141\llvm-9.0.0-vc141-x64\ -DLLVM_BUILD_LLVM_DYLIB=OFF -DLLVM_BUILD_TOOLS=OFF -G"Visual Studio 15 2017 Win64" -Thost=x64
```

**Comment by learn-more** [comment]
to be clear, the off_t is always supposed to be 64 bit, or only on x64 builds?

**Comment by solemnwarning** [comment]
It should be 64-bit on platforms that support large files, which includes 32-bit Windows I think (has `_ftelli64()` and friends).

**Comment by learn-more** [comment]
wxWidgets also has something to say on this:
```
#if defined(__VISUALC__)
    typedef _off_t off_t;
#endif
```

**Comment by learn-more** [comment]
A decent alternative is in progress.
