### ISSUE TITLE
Allow offsets to be relative to arbitrary value

### ISSUE THREAD

**Issue by solemnwarning** [solemnwarning/rehex#7]
Make it so the offsets used in the UI can be adjusted by an arbitrary amount, for example to help finding things relative to a DLL base address, or to a point in the file.

**Comment by solemnwarning** [comment]
Rather than making this a file-wide offset adjustment, it might be better to have multiple regions of (non-overlapping) ranges specifiable - then executables (for example) can have the address spaces of different sections mapped appropriately, probably displayed in addition to the file offsets somehow.

**Comment by alexforencich** [comment]
Supporting independent sections is really the way to go.  Perhaps you need multiple views - "raw" file view, and sectioned view (for files that support multiple sections).  Additionally, each section should be a completely independent address space.  This is useful for any file type that can be sparse (intel hex) and/or supports defined, specific, relocatable sections (elf, etc.).

**Comment by solemnwarning** [comment]
This has been implemented on the `segments` branch and will probably be merged soon. Outstanding issues:

* Selecting between segments in the virtual segments view produces nonsensical results.
* Some operations (e.g. setting a mapping) take multiple undo operations.

**Comment by solemnwarning** [comment]
Opened issues #125 and #126 to track outstanding bugs.
