### ISSUE TITLE
Inline comments throw off line-alignment

### ISSUE THREAD

**Issue by learn-more** [solemnwarning/rehex#84]
Using 16 bytes per line, 1 byte per group the data is 'aligned' on multiples of 0x10

When inserting a comment on data that does not span a full line (see attached screenshot),
the data below that comment is no longer aligned to what it was before, but to whatever the first byte after the comment happens to be.

imo it would be nicer if the 'rest' of the line would be displayed on it's own (possibly aligned to where it would be horizontally),
and the rest of the data is still aligned on 0x10 boundaries.

![image](https://user-images.githubusercontent.com/610685/92698514-c7995400-f34c-11ea-8ebe-2df598c6457f.png)

**Comment by solemnwarning** [comment]
I did originally intend to have this as an option, haven't got around to it yet though.

**Comment by learn-more** [comment]
> I did originally intend to have this as an option, haven't got around to it yet though.

In my opinion, not everything should be an option.
Some things are part of the software, and some things should be user-configurable.

**Comment by solemnwarning** [comment]
Fix for this pushed to the `dr-first-line-pad` branch, pending further testing.

I think it might want disabling when nested comments and dynamic line lengths are enabled, as the results can look a bit wonky.

**Comment by solemnwarning** [comment]
Merged to master. Data is only padded to preserve alignment when bytes per line is set to a fixed value.
