### ISSUE TITLE
ToolWindow parenting issue

### ISSUE THREAD

**Issue by learn-more** [solemnwarning/rehex#90]
The current design has the document as the parent of the tool windows (both h and v).
In my opinion it would be better to make the main window the parent of the tool windows.

- This would consume less memory (when opening multiple documents)
- This would make it possible to have an output-like window as seen in f.e. IDA pro that is session wide (not document wide).
- This would probably make event routing slightly more complex

What is your view on this?

**Comment by solemnwarning** [comment]
Are you considering changing this as part of reworking the tool window sizing code, or is it just something that occurred to you in passing?

I think the implementation would be a bit more complicated, since it'd have to show/hide tool tabs when switching document tabs, and you'd lose the state (position) of the sizers too, but don't have a strong opinion if there's a clean way of implementing it.

Output window is a valid point, although I'm not sure what it'd be used for right now (ideas?), not too concerned about the additional memory usage either, since I'm **assuming** the additional windows only use a few k of memory (please do correct me if they actually do use nontrivial amounts of memory...).

I don't *think* the event routing would be too difficult, since tool panels are already siblings of the actual Document/DocumentCtrl objects and have dynamic event bindings set up.

**Comment by learn-more** [comment]
> Are you considering changing this as part of reworking the tool window sizing code, or is it just something that occurred to you in passing?
> 
> I think the implementation would be a bit more complicated, since it'd have to show/hide tool tabs when switching document tabs, and you'd lose the state (position) of the sizers too, but don't have a strong opinion if there's a clean way of implementing it.
> 
> Output window is a valid point, although I'm not sure what it'd be used for right now (ideas?), not too concerned about the additional memory usage either, since I'm **assuming** the additional windows only use a few k of memory (please do correct me if they actually do use nontrivial amounts of memory...).
> 
> I don't _think_ the event routing would be too difficult, since tool panels are already siblings of the actual Document/DocumentCtrl objects and have dynamic event bindings set up.

Not related to the tool window sizing code, this is something that occurred to me while toying with python bindings.
(Hence the output window)
However when toying with this a bit more, there need to be 2 output windows: 1 'global' output (scripting initialization and whatnot), and one 'output' for the script on the current document (assuming they should also act 'per document' as the current toolwindows do.

I briefly considered changing the h_tools to be outside the doc, but it might make sense to wait for that until there is a clear direction for plugins.

**Comment by solemnwarning** [comment]
Interesting :)

I've been thinking about plugins on and off, but still want to get the editor a bit more complete and have more of an idea as to what plugins need to be *capable* of before starting on it.

What I think I have settled on though, is for the primary plugin language to be C++, perhaps even only statically linked as it is now, but then have support for script (I was thinking of experimenting with Lua first) plugins provided via separate plugins, keeping all the glue/etc out of the core editor code.

**Comment by solemnwarning** [comment]
I was thinking about implementing session-wide output windows by adding a "global" flag to ToolWindow instances, any that are true would be reparented when switching tab so the same instance is always visible, but #12 will involve multiple instances of MainWindow existing, each potentially with its own "global" log ToolPanel instance.

Maybe the global log should instead be implemented as a common buffer referenced by each instance of the global log ToolPanel, or as a separate window, or something else?

**Comment by learn-more** [comment]
> I was thinking about implementing session-wide output windows by adding a "global" flag to ToolWindow instances, any that are true would be reparented when switching tab so the same instance is always visible, but #12 will involve multiple instances of MainWindow existing, each potentially with its own "global" log ToolPanel instance.
> 
> Maybe the global log should instead be implemented as a common buffer referenced by each instance of the global log ToolPanel, or as a separate window, or something else?

I would not change the application to have multiple MainWindow's per process, but instead figure out how to transfer data cross-process.

Otherwise it would be very confusing for a user why he can drag from some windows, but not others.
Additionally, this also prevent the design of the application from becoming more complex.

**Comment by solemnwarning** [comment]
> I would not change the application to have multiple MainWindow's per process, but instead figure out how to transfer data cross-process.
> 
> Otherwise it would be very confusing for a user why he can drag from some windows, but not others.

Maybe. Part of the above work would also include making it so only one process exists - starting another would just send an "open" or "new window" command to any existing one.

Moving the entire state of a tab between processes (including toolpanels, undo/redo history, modified data) isn't going to be easy, especially with plugins potentially holding onto state as well.

**Comment by solemnwarning** [comment]
I prototyped a console on the `console-prototype` branch loosely inspired by the one in your Lua prototype. Only supports a single app-wide console right now, but is structured to allow arbitrary buffers/views for implementing per-document or per-plugin or created-at-runtime consoles as necessary in the future.

Will probably roll it into my wxlua prototype and iterate that a bit more soon(ish).

**Comment by solemnwarning** [comment]
Closing this for now.
