### ISSUE TITLE
Build faiure against latest capstone

### ISSUE THREAD

**Issue by aslak3** [solemnwarning/rehex#93]
```
g++ -Wall -std=c++11 -ggdb -I. -Iinclude/ -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 \
-I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -DNDEBUG \
-MT src/disassemble.o -MMD -MP -MF .d/src/disassemble.o.Td -c -o src/disassemble.o src/disassemble.cpp
src/disassemble.cpp:100:1: error: invalid conversion from ‘int’ to ‘cs_mode’ [-fpermissive]
 };
 ^
```

This is with master as of this posting. Did not test earlier revisions.

Capstone is taken from there github repo, again the latest  as per this posting. I only wanted the latest Capstone for 68000 support, so I removed all bar the 68000 line from disassemble.cpp and got a working build.

**Comment by solemnwarning** [comment]
This week in "solemnwarning did a thing and didn't bother to test it actually works" (the 6502 support).

Fixed in ac693d83a51c42681889c1c994744ea44c67394d.
