### ISSUE TITLE
Double clicking on a comment in the Comments section doesn't do anything

### ISSUE THREAD

**Issue by hogsy** [solemnwarning/rehex#96]
Expected this to take me to the comment offset, right now it does nothing. Would probably be more useful if it jumped the user to the offset by default.

![zZAUcQkQ6K](https://user-images.githubusercontent.com/1946366/98826958-3a4aac80-242e-11eb-9692-06bdfe33ea15.gif)

**Comment by solemnwarning** [comment]
Implemented in 5a3a302019790e8f825d68cbc0a5056e02d990a6.
